/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FafireImport } from './routes/fafire'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FafireRoute = FafireImport.update({
  id: '/fafire',
  path: '/fafire',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fafire': {
      id: '/fafire'
      path: '/fafire'
      fullPath: '/fafire'
      preLoaderRoute: typeof FafireImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fafire': typeof FafireRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fafire': typeof FafireRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/fafire': typeof FafireRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fafire'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fafire'
  id: '__root__' | '/' | '/fafire'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FafireRoute: typeof FafireRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FafireRoute: FafireRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/fafire"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/fafire": {
      "filePath": "fafire.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
